[package]
name = "do-not-publish/wave-survival"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Stew = "data-oriented-house/rbxstew@0.3.1"
Sandwich = "data-oriented-house/sandwich@2.1.0"